export const EMPTY_RECIPE = {
  id: null,
  author: null,
  parent: null,
  title: '',
  images: [],
  followers: [],
  yield: '',
  yield_unit: '',
  ingredients: [],
  prep_time: '',
  prep_steps: [],
  cook_time: '',
  cook_steps: [],
  finish_steps: [],
  tags: [],
  fork_history: [],
  historyRecipes: [],
};
